apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-jwt
  namespace: mock-trading-platform-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: mock-trading-platform-dev-aws-secretsmanager
  target:
    name: auth-jwt
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: exchange/dev/auth-jwt
        property: JWT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-db
  namespace: mock-trading-platform-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: mock-trading-platform-dev-aws-secretsmanager
  target:
    name: app-db
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: exchange/dev/app-db
        property: DATABASE_URL
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: exchange/dev/app-db
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-nats
  namespace: mock-trading-platform-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: mock-trading-platform-dev-aws-secretsmanager
  target:
    name: app-nats
  data:
    - secretKey: NATS_URL
      remoteRef:
        key: exchange/dev/app-nats
        property: NATS_URL
    - secretKey: NATS_TOKEN
      remoteRef:
        key: exchange/dev/app-nats
        property: NATS_TOKEN
