apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: mock-trading-platform-dev-aws-secretsmanager
  namespace: mock-trading-platform-dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2 # TODO(dev): 실제 AWS region으로 치환
      role:  # TODO(dev): SecretStore assume role ARN 치환
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
